#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "GreenHouse"
  https://create.arduino.cc/cloud/things/3c66615d-5a00-4d2a-94c9-374d65b24d08 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int humidity;
  int soilMoisture;
  int temparature;
  bool motorOn;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
  #include <Wire.h>
  #include <LiquidCrystal_I2C.h>
  #include "DHT.h"

  // ====== LCD & DHT Configuration ======
  #define DHTPIN 4          // DHT sensor pin
  #define DHTTYPE DHT11     // or DHT22
  DHT dht(DHTPIN, DHTTYPE);

  LiquidCrystal_I2C lcd(0x27, 16, 4);  // LCD I2C address (try 0x3F if 0x27 not working)

  // ====== LED Pins ======
  #define TEMP_RED 15
  #define TEMP_GREEN 2
  #define HUM_RED 18
  #define HUM_GREEN 19


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

   // Initialize DHT
    dht.begin();

    // Initialize LCD
    lcd.init();
    lcd.backlight();

    // Initialize LEDs
    pinMode(TEMP_RED, OUTPUT);
    pinMode(TEMP_GREEN, OUTPUT);
    pinMode(HUM_RED, OUTPUT);
    pinMode(HUM_GREEN, OUTPUT);
    pinMode(23,OUTPUT);

    lcd.setCursor(0, 0);
    lcd.print("Temp & Humidity");
    lcd.setCursor(0, 1);
    lcd.print("Initializing...");
    delay(2000);
    lcd.clear();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
   float h = dht.readHumidity();
    float t = dht.readTemperature();

    temparature = t;
    humidity = h;

    // Check for sensor errors
    if (isnan(h) || isnan(t)) {
      Serial.println("Failed to read from DHT sensor!");
      lcd.clear();
      lcd.setCursor(0, 0);
      lcd.print("Sensor Error");
      delay(2000);
      return;
    }

    // Print to Serial
    Serial.print("Temp: ");
    Serial.print(t);
    Serial.print(" °C | Hum: ");
    Serial.print(h);
    Serial.println(" %");

    // Display on LCD
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print("Temp: ");
    lcd.print(t, 1);
    lcd.print(" C");

    lcd.setCursor(0, 1);
    lcd.print("Hum:  ");
    lcd.print(h, 1);
    lcd.print(" %");

    // ====== Temperature LED Control ======
    if (t > 31.0) {
      digitalWrite(TEMP_RED, HIGH);
      digitalWrite(TEMP_GREEN, LOW);
    } else {
      digitalWrite(TEMP_RED, LOW);
      digitalWrite(TEMP_GREEN, HIGH);
    }

    // ====== Humidity LED Control ======
    if (h > 70.0) {
      digitalWrite(HUM_RED, HIGH);
      digitalWrite(HUM_GREEN, LOW);
    } else {
      digitalWrite(HUM_RED, LOW);
      digitalWrite(HUM_GREEN, HIGH);
    }

    delay(2000); // update every 2 seconds
  
}

/*
  Since Temparature is READ_WRITE variable, onTemparatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemparatureChange()  {
  // Add your code here to act upon Temparature change
}

/*
  Since Humidity is READ_WRITE variable, onHumidityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHumidityChange()  {
  // Add your code here to act upon Humidity change
}


/*
  Since SoilMoisture is READ_WRITE variable, onSoilMoistureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSoilMoistureChange()  {
  // Add your code here to act upon SoilMoisture change
}

/*
  Since MotorOn is READ_WRITE variable, onMotorOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotorOnChange()  {
  // Add your code here to act upon MotorOn change
  if(motorOn){
    digitalWrite(23, HIGH);
  }else{
     digitalWrite(23, OFF);
  }

  serial.println("Motor ON");
}

