// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3f0417e8-cb29-4fc0-ad33-15b53f588adb";

const char SSID[]               = "Dialog 4G 713";    // Network SSID (name)
const char PASS[]               = "3aF15bFF";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "VK!#XM?z2IPf7OiE@8rLSQzDz";    // Secret device password

void onHumidityChange();
void onSoilMoistureChange();
void onTemparatureChange();
void onMotorOnChange();

int humidity;
int soilMoisture;
int temparature;
bool motorOn;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(soilMoisture, READWRITE, ON_CHANGE, onSoilMoistureChange);
  ArduinoCloud.addProperty(temparature, READWRITE, ON_CHANGE, onTemparatureChange);
  ArduinoCloud.addProperty(motorOn, READWRITE, ON_CHANGE, onMotorOnChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
