    /* 
      Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
      https://create.arduino.cc/cloud/things/5bd0ed21-d850-47df-89a1-e1297a06ded0 

      Arduino IoT Cloud Variables description

      The following variables are automatically generated and updated when changes are made to the Thing

      String mobileNum;
      float humid;
      float temp;
      int slider;
      bool led;

      Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
      which are called when their values are changed from the Dashboard.
      These functions are generated with the Thing and added at the end of this sketch.
    */

    #include "thingProperties.h"
    #include <DHT.h>

    // DHT sensor configuration
    #define DHTPIN 15       // Change to your GPIO pin
    #define DHTTYPE DHT11   // or DHT22

    #include <ESP32Servo.h>

    const int micPin = 35;  // AO to analog input
    const int soundPin = 4;  // AO to analog input
    Servo myServo;           // Create servo object
    int servoPin = 13;       // GPIO pin for servo signal 


    DHT dht(DHTPIN, DHTTYPE);

    const int ledPin = 2;          // GPIO 2
    const int freq = 5000;         // PWM frequency (Hz)
    const int pwmChannel = 0;      // Choose a PWM channel (0–15)
    const int resolution = 8;      // 8-bit resolution (0–255)

    void setup() {
      // Initialize serial and wait for port to open:
      Serial.begin(115200);
      // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
      delay(1500); 

        pinMode(2, OUTPUT);
        dht.begin();
        myServo.setPeriodHertz(50);      // Standard servo frequency
        myServo.attach(servoPin, 500, 2400); // Pin, min & max pulse width in µs

      // Defined in thingProperties.h
      initProperties();

      // Connect to Arduino IoT Cloud
      ArduinoCloud.begin(ArduinoIoTPreferredConnection);
      
      /*
        The following function allows you to obtain more information
        related to the state of network and IoT Cloud connection and errors
        the higher number the more granular information you’ll get.
        The default is 0 (only errors).
        Maximum is 4
    */
      setDebugMessageLevel(2);
      ArduinoCloud.printDebugInfo();



    }

    void loop() {
      ArduinoCloud.update();
      // Your code here 
      
        analogWrite(2, slider); // Set brightness
        delay(slider);
        analogWrite(2, 0); // Set brightness
        delay(slider);

          float tmp = dht.readTemperature();
          float hum = dht.readHumidity();

          if (!isnan(tmp) && !isnan(hum)) {
            temp = round(tmp*10) / 10.0;
            humid = round(hum*10) / 10.0;
          }

       int soundState = digitalRead(soundPin);
      Serial.println(soundState);
        if (soundState == LOW) {
          Serial.println("💥 Sound detected!");
        }

          int micValue = analogRead(micPin); // Range: 0–4095
          Serial.print("Mic level: ");
          Serial.println(micValue);
          delay(50);

          
    }


    /*
      Since Led is READ_WRITE variable, onLedChange() is
      executed every time a new value is received from IoT Cloud.
    */
    void onLedChange()  {
      // Add your code here to act upon Led change
      digitalWrite(2, led); // Turn the LED ON
      delay(1000);           // Wait for 1 second
    }

    /*
      Since Slider is READ_WRITE variable, onSliderChange() is
      executed every time a new value is received from IoT Cloud.
    */
    void onSliderChange()  {
      // Add your code here to act upon Slider change
      analogWrite(2, slider); // Set brightness
        delay(50);

      myServo.write(map(slider, 0, 255, 0, 180));

      if(slider > 100)
      {
        led = true;
      }else{
        led= false;
      }
      
    }

    /*
      Since Temp is READ_WRITE variable, onTempChange() is
      executed every time a new value is received from IoT Cloud.
    */
    void onTempChange()  {
      // Add your code here to act upon Temp change
    }

    /*
      Since Humid is READ_WRITE variable, onHumidChange() is
      executed every time a new value is received from IoT Cloud.
    */
    void onHumidChange()  {
      // Add your code here to act upon Humid change
    }

    /*
      Since MobileNum is READ_WRITE variable, onMobileNumChange() is
      executed every time a new value is received from IoT Cloud.
    */
    void onMobileNumChange()  {
      // Add your code here to act upon MobileNum change
    }